language: node_js

node_js:
   "8.6.0"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  email: prithweedas123@gmail.com
  name: Prithwee Das
  target-branch: gh-pages
  on:
    branch: master